sty = {
	"MENU_STD_TITLE":		{"style":"boxTitle"},
	"MENU_STD_BUT":			{"style":"stdButtonMenu light_blue connect"},
	"BOX_STD_TITLE":		{"style":"boxTitle"},
	"SUBBOX_STD_TITLE":		{"style":"subBoxTitle"},
	"STD_BUTTON":			{"style":"stdButton light_blue"},

	"ACTION_CONFIG":{"title":"CONFIG","icon":"img/config.png","shortcut":"Ctrl+P"},
	"ACTION_EXIT":{"title":"EXIT_APP","icon":"img/exit.png","shortcut":"CTRL+Q"},
	"ACTION_HOME":{"title":"HOME","icon":"img/op.png","shortcut":"Ctrl+H"},
	"ACTION_STOP":{"title":"STOP","icon":"img/stop2.png","shortcut":"Ctrl+S"},

	"BUT_ADD":   	   	   	{"tooltip":"ADD", "style":"stdButIcon add"},
	"BUT_ADD_NODE":   	   	{"tooltip":"ADD", "style":"stdButIcon add"},
	"BUT_ADD_EX_FIELD":    	{"tooltip":"ADD", "style":"stdButIcon add"},
	"BUT_ADD_HLINE":    	{"style":"stdButton purple arrow_right"},
	"BUT_ADD_VLINE":    	{"style":"stdButton purple arrow_up"},
	"BUT_CIRCUIT_CONF":    	{"title":"CIRCUIT","style":"stdButtonMenu light_blue circuit"},
	"BUT_COM_CONF":			{"title":"COM","style":"stdButtonMenu light_blue communication"},
	"BUT_CONNECT":			{"title":"CONNECT","style":"stdButtonMenu purple connect"},
	"BUT_CONF":       	   	{"title":"CONFIG","style":"stdButtonMenu butFirst heavy_blue config"},
	"BUT_CONFIG":      		{"title":"CONFIG","style":"stdButton green config"},
	"BUT_CONNECT":      	{"title":"CONNECT","style":"stdButton green config"},
	"BUT_CONFIG_CONF":    	{"title":"CONFIG_GLOBAL","style":"stdButtonMenu light_blue option"},
	"BUT_CONFIG_TEST":      {"title":"CONFIG","style":"stdButtonMenu blue config"},
	"BUT_DEL":			   	{"tooltip":"DEL", "style":"stdButton red del"},
	"BUT_DISCONNECT_TEST":		{"title":"DISCONNECT","style":"stdButtonMenu red disconnect"},
	"BUT_DISCONNECT":		{"title":"DISCONNECT","style":"stdButton red disconnect"},
	"BUT_EDIT":			   	{"tooltip":"EDIT", "style":"stdButton light_blue edit"},
	"BUT_EQ_CONF":	   	   	{"title":"EQUIP","style":"stdButtonMenu light_blue equipment"},		
	"BUT_EX_CONF":	   	   	{"title":"EXPANSION","style":"stdButtonMenu light_blue expansion"},
	"BUT_GET_INFO_TEST":			{"title":"INFO","style":"stdButtonMenu green update"},				
	"BUT_IN_OUT_CONF":	   	{"title":"IN_OUT","style":"stdButtonMenu light_blue in_out"},
	"BUT_MONITORING_CONF": 	{"title":"MONITORING","style":"stdButtonMenu light_blue monitoring"},
	"BUT_NODE_CONF":  	   	{"title":"MODULE","style":"stdButtonMenu light_blue module"},
	"BUT_OK":				{"title":"OK","style":"stdButton green"},
	"BUT_ON":				{"title":"ON","style":"stdButton green","expand":False},
	"BUT_OFF":				{"title":"OFF","style":"stdButton red","expand":False},
	"BUT_OP":         	   	{"title":"OP",    "style":"stdButtonMenu butFirst heavy_blue op"},
	"BUT_RESUME_CONF":    	{"title":"RESUME","style":"stdButtonMenu light_blue resume"},
	"BUT_ROTATE":         	{"style":"stdButton heavy_blue rotate"},
	"BUT_SEND":            	{"title":"SEND","style":"stdButton light_blue ok"},
	"BUT_SUB_CIRCUIT_CONF": {"title":"SUB_CIRCUIT","style":"stdButtonMenu light_blue circuit"},
	"BUT_START":			{"title":"START","style":"stdButton green start","expand":False},
	"BUT_STOP":				{"title":"STOP","style":"stdButton red stop","expand":False},
	"BUT_TEST_EQ_CONF":		{"title":"TEST_EQ",    "style":"stdButtonMenu light_blue test"},
	"BUT_UNI_CIRCUIT_CONF": {"title":"UNI_CIRCUIT","style":"stdButtonMenu light_blue circuit"},
	"BUT_UPDATE":			{"style":"stdButton light_blue update"},
	"BUT_VISU_CONF":		{"title":"VISU","style":"stdButtonMenu light_blue visu"},
	
	"FIELD":				{"style":"field","title":""},

	"LAB_ANA_TYPE":     {"title":"ANA_TYPE","style":"label"},
	"LAB_CHANNEL":		{"title":"CHANNEL","style":"label"},
	"LAB_CONFIG":		{"title":"CONFIGTXT","style":"label"},
	"LAB_CONNECTED":	{"title":"CONNECTEDTXT","style":"label"},
	"LAB_DELTA":		{"title":"DELTA","style":"label"},
	"LAB_EQUIP":		{"title":"EQUIP","style":"label"},
	"LAB_EX":			{"title":"EXPANSION","style":"label"},
	"LAB_GROUP":		{"title":"GROUP","style":"label"},
	"LAB_EQUIP_NO":		{"title":"EQUIP_NO","style":"label"},
	"LAB_EX_NO":		{"title":"EX_NO","style":"label"},
	"LAB_INDEX":		{"title":"INDEX","style":"label"},
	"LAB_MAX": 			{"title":"MAX","style":"label"},
	"LAB_MIN": 			{"title":"MIN","style":"label"},
	"LAB_MODULE": 		{"title":"MODULE","style":"label"},
	"LAB_NAME":			{"title":"NAME","style":"label"},
	"LAB_NODE_ADDRESS": {"title":"NODE_ADDRESS","style":"label"},
	"LAB_NODE_NAME": 	{"title":"NODE_NAME","style":"label"},
	"LAB_NODE_TYPE":	{"title":"MODULE_TYPE","style":"label"},
	"LAB_NUM":			{"title":"NUM","style":"label"},
	"LAB_NUM_NODE":  	{"title":"NUM_NODE","style":"label"},
	"LAB_NUM_EX":	 	{"title":"NUM_EX","style":"label"},
	"LAB_NUM_IN_TOR":	{"title":"IN_TOR","style":"label"},
	"LAB_NUM_OUT_TOR":	{"title":"OUT_TOR","style":"label"},
	"LAB_NUM_IN_ANA":	{"title":"IN_ANA","style":"label"},
	"LAB_NUM_OUT_ANA":	{"title":"OUT_ANA","style":"label"},
	"LAB_RANK": 		{"title":"RANK","style":"label"},
	"LAB_REPLI": 		{"title":"REPLI","style":"label"},
	"LAB_STARTAT": 		{"title":"STARTAT","style":"label"},
	"LAB_SUBINDEX": 	{"title":"SUBINDEX","style":"label"},
	"LAB_SUB_CIRCUIT": 	{"title":"SUB_CIRCUIT","style":"label"},
	"LAB_TYPE": 		{"title":"TYPE","style":"label"},
	"LAB_UNIT": 		{"title":"UNIT","style":"label"},
	"LAB_UNI_CIRCUIT": 	{"title":"UNI_CIRCUIT","style":"label"},
	"LAB_VAL": 			{"title":"VAL","style":"label"},

	"IMG_NO":			{"style":"i_icon i_no"},
	"IMG_NO_MIN":		{"style":"min_icon i_no"},
	"IMG_PUMP":			{"style":"max_icon i_pump"},
	"IMG_VALVE_TOR":	{"style":"i_icon i_valve"},
	"IMG_WHAT_MIN":		{"style":"min_icon i_what"},
	"IMG_WHAT":			{"style":"i_icon i_what"},
	"IMG_YES":			{"style":"i_icon i_yes"},
	"IMG_YES_MIN":		{"style":"min_icon i_yes"},

	"LINE_V":			{"style":"line_v"},
}
